### ISSUE TITLE
I got NameError

### ISSUE THREAD

**Issue by CaBayTungTang** [doubleplusc/Line-sticker-downloader#7]
The same happen with "y"

Traceback (most recent call last):
  File "C:\Users\Ashes\Downloads\Compressed\Line-sticker-downloader-master\sticker_dl.py", line 137, in <module>
    main()
  File "C:\Users\Ashes\Downloads\Compressed\Line-sticker-downloader-master\sticker_dl.py", line 30, in main
    pack_ext = input("\nAnimated stickers available! \nEnter png, apng, or both, anything else to exit: ")
  File "<string>", line 1, in <module>
NameError: name 'apng' is not defined

**Comment by KingGeneral** [comment]
i made a fix here : 
https://github.com/doubleplusc/Line-sticker-downloader/pull/9
